spring:
  application:
    name: logging

  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
    username: '${DB_USERNAME:sa}'
    password: '${DB_PASSWORD:password}'

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml

  h2:
    console:
      enabled: '${ENABLE_H2_CONSOLE:true}'
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: "health"
server:
  port: '${PORT:8080}'
