name: Logging service CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change to app directory
        run: cd app

      - name: Maven package
        run: mvn -B package --file app/pom.xml
        
      - name: Maven test
        run: mvn test --file app/pom.xml
